[package]
name = "Advent-of-Code-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2"
owo-colors = "3"
log = "0.4"
fern = "0.6"
